name: Run remote make command
inputs:
  target:
    required: true
    type: string

outputs:
  result:
    value: ${{ steps.make-run.outputs.result }}

runs:
  using: 'composite'
  steps:
    - name: Run make command remotely
      id: make-run
      run: |
        echo ::set-output name=result::$(ssh -i ${{ env.SSH_KEY_PATH }} ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} 'cd recap && make ${{ inputs.target }}')
      shell: bash
